export const LOG_LIMIT = 120;

export const CLAMPED_STATS = [
  "health",
  "fear",
  "greed",
  "trust",
  "morality",
  "influence",
];

export const TRACKED_STAT_DELTAS = [
  "health",
  "fear",
  "greed",
  "trust",
  "morality",
  "influence",
];

export const DEFAULT_BOAT_STATE = {
  turn: 1,
  max_turn: 10,
  water: 5,
  food: 3,
  stability: 70,
  rescue_chance: 30,
  storm_level: 0,
  minor_power: 3,
  max_minor_power: 3,
  major_power: 4,
  chapter_finished: false,
  judgement_done: false,
};

export const DEFAULT_CHARACTERS = [
  {
    id: "chairman",
    name: "Mr. Vale",
    name_key: "character.chairman.name",
    role: "Wealthy Chairman",
    role_key: "character.chairman.role",
    alive: true,
    health: 100,
    fear: 35,
    greed: 85,
    trust: 40,
    morality: 30,
    influence: 70,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
  {
    id: "nurse",
    name: "Clara",
    name_key: "character.nurse.name",
    role: "Nurse",
    role_key: "character.nurse.role",
    alive: true,
    health: 100,
    fear: 30,
    greed: 20,
    trust: 70,
    morality: 85,
    influence: 45,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
  {
    id: "soldier",
    name: "Grant",
    name_key: "character.soldier.name",
    role: "Ex-Soldier",
    role_key: "character.soldier.role",
    alive: true,
    health: 100,
    fear: 25,
    greed: 45,
    trust: 50,
    morality: 55,
    influence: 75,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
  {
    id: "influencer",
    name: "Mia",
    name_key: "character.influencer.name",
    role: "Influencer",
    role_key: "character.influencer.role",
    alive: true,
    health: 100,
    fear: 45,
    greed: 65,
    trust: 55,
    morality: 45,
    influence: 80,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
  {
    id: "elder",
    name: "Old Theo",
    name_key: "character.elder.name",
    role: "Elderly Passenger",
    role_key: "character.elder.role",
    alive: true,
    health: 70,
    fear: 50,
    greed: 15,
    trust: 60,
    morality: 75,
    influence: 20,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
  {
    id: "stowaway",
    name: "Nox",
    name_key: "character.stowaway.name",
    role: "Stowaway",
    role_key: "character.stowaway.role",
    alive: true,
    health: 90,
    fear: 55,
    greed: 50,
    trust: 20,
    morality: 50,
    influence: 25,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    judgement: "",
  },
];

export const TRANSLATIONS = {
  en: {
    "language.en": "English",
    "language.ko": "Korean",

    "ui.title.game": "The Judge of Survival",
    "ui.title.chapter_1": "Chapter 1 - Lifeboat of Greed",
    "ui.status.turn": "Turn: {turn}/{max_turn}",
    "ui.status.water": "Water: {water}",
    "ui.status.stability": "Stability: {stability}",
    "ui.status.rescue": "Rescue: {rescue}%",
    "ui.status.minor_power": "Minor: {minor} / {max_minor}",
    "ui.status.major_power": "Major: {major}",
    "ui.status.language": "Language",
    "ui.panel.characters": "Characters",
    "ui.panel.minor_powers": "Minor Powers",
    "ui.panel.major_powers": "Major Powers",
    "ui.power_status.minor": "Minor Power: {minor} / {max_minor}",
    "ui.power_status.major": "Major Power: {major}",
    "ui.button.whisper_fear": "Whisper Fear",
    "ui.button.nudge_greed": "Nudge Greed",
    "ui.button.seed_doubt": "Seed Doubt",
    "ui.button.false_comfort": "False Comfort",
    "ui.button.heavy_silence": "Heavy Silence",
    "ui.button.reduce_water": "Reduce Water",
    "ui.button.rumor": "Spread False Rumor",
    "ui.button.hidden_food": "Place Hidden Food",
    "ui.button.storm": "Approach Storm",
    "ui.button.next_turn": "Next Turn",
    "ui.button.finish": "Finish Chapter",
    "ui.button.restart": "Restart",
    "ui.character.status_alive": "Alive",
    "ui.character.status_dead": "Dead",
    "ui.character.summary": "{name} - {role}",
    "ui.character.vitals": "{status} | HP {health} | Fear {fear} | Greed {greed}",
    "ui.character.traits": "Trust {trust} | Morality {morality} | Influence {influence}",
    "ui.character.judgement": "Judgement: {judgement}",

    "character.chairman.name": "Mr. Vale",
    "character.chairman.role": "Wealthy Chairman",
    "character.nurse.name": "Clara",
    "character.nurse.role": "Nurse",
    "character.soldier.name": "Grant",
    "character.soldier.role": "Ex-Soldier",
    "character.influencer.name": "Mia",
    "character.influencer.role": "Influencer",
    "character.elder.name": "Old Theo",
    "character.elder.role": "Elderly Passenger",
    "character.stowaway.name": "Nox",
    "character.stowaway.role": "Stowaway",

    "judgement.sacrificial_victim": "Sacrificial Victim",
    "judgement.victim": "Victim",
    "judgement.betrayer": "Betrayer",
    "judgement.hypocrite": "Hypocrite",
    "judgement.instigator": "Instigator",
    "judgement.corrupted_survivor": "Corrupted Survivor",
    "judgement.survivor": "Survivor",
    "judgement.unjudged": "Unjudged",

    "log.game_start": "The trial begins. Six souls wake inside a lifeboat.",
    "log.power_reduce_water": "The Judge dries one bottle of water. The boat grows quieter.",
    "log.power_rumor": "A rumor spreads: someone on this boat has been hiding the truth.",
    "log.power_hidden_food": "A small packet of emergency food appears beneath someone's seat.",
    "log.power_storm": "Dark clouds gather. The lifeboat begins to shake.",
    "log.already_judged": "The trial is already judged. Restart to begin again.",
    "log.no_minor_power": "The Judge has no minor power left for subtle interference.",
    "log.no_major_power": "The Judge has no major power left for such a heavy intervention.",
    "log.finish_not_ready": "The trial is not ripe for final judgement. Let the sea speak longer.",
    "log.final_judgement_header": "--- Final Judgement ---",
    "log.judgement_result": "{name} -> {judgement}",
    "log.death": "{name} can no longer endure the trial.",
    "log.capsize": "The lifeboat capsizes. The sea takes the final vote.",
    "log.max_turn_passed": "The tenth turn passes. The trial can hold no more.",
    "log.too_few": "Too few souls remain to continue the trial.",

    "log.minor_whisper_fear": "The Judge whispers into {name}'s fear.\n{name} looks at the others as if they are already enemies.",
    "log.minor_nudge_greed": "The Judge gently sharpens {name}'s hunger.\n{name} starts counting the supplies again.",
    "log.minor_seed_doubt": "A small doubt blooms around {name}.\nNo one says it aloud, but everyone feels it.",
    "log.minor_false_comfort": "The Judge grants a moment of false comfort.\nFor a breath, they believe rescue is closer than it is.",
    "log.minor_heavy_silence": "The sea falls silent.\nIn that silence, every soul becomes a little smaller.",

    "event.hidden_resource_found": "{name} is caught hiding emergency food.\n{name}: I was saving it for the right moment. You would have wasted it.",
    "event.exile_the_weak": "{name}: We need to be realistic. The weakest among us may doom everyone.",
    "event.secret_water_drinking": "{name} drinks from the water supply while the others look away.\n{name}: I only took what I needed to stay useful.",
    "event.nurse_protects": "{name} tends to the weakest passenger, even as her own hands begin to shake.\n{name}: If we start choosing who deserves care, we are already lost.",
    "event.soldier_takes_order": "{name} raises his voice and forces everyone into silence.\n{name}: Panic kills faster than hunger. From now on, we follow order.",
    "event.influencer_instigates": "{name} speaks softly, but everyone listens.\n{name}: I hate to say this, but some people here are making us unsafe.",
    "event.stowaway_witch_hunt": "Suspicion turns toward {name}.\nSomeone whispers: We do not even know why he was on the ship.",
    "event.voluntary_sacrifice": "{name} looks at the sinking edge of the boat.\n{name}: If one less body gives the rest of you a chance, then remember me kindly.",
    "event.boat_damage": "The lifeboat cracks under the weight and the waves.",
    "event.panic_outburst": "{name} snaps under the pressure and lashes out.\n{name}: Stay away from me! I will not die here!",
    "event.rescue_signal": "A distant light appears beyond the waves. Rescue may finally be near.",
    "event.silent_turn": "No one speaks. The sea answers for them.",

    "web.nav.trial": "Trial",
    "web.nav.roster": "Roster",
    "web.nav.log": "Log",
    "web.nav.judgement": "Judgement",
    "web.panel.recent_log": "Recent Log",
    "web.panel.lifeboat": "Lifeboat",
    "web.panel.supplies": "Supplies",
    "web.panel.outcomes": "Outcomes",
    "web.status.alive": "Alive: {count}",
    "web.status.storm": "Storm: {level}",
    "web.status.food": "Food: {food}",
    "web.status.hidden": "Hidden food",
    "web.status.counts": "Betrayal {betrayal} | Sacrifice {sacrifice} | Hypocrisy {hypocrisy} | Instigation {instigation}",
    "web.judgement.pending": "Final judgement is not complete.",
    "web.stat.health": "HP",
    "web.stat.fear": "Fear",
    "web.stat.greed": "Greed",
    "web.stat.trust": "Trust",
    "web.stat.morality": "Morality",
    "web.stat.influence": "Influence",
  },

  ko: {
    "language.en": "영어",
    "language.ko": "한국어",

    "ui.title.game": "생존의 심판자",
    "ui.title.chapter_1": "1장 - 탐욕의 구명보트",
    "ui.status.turn": "턴: {turn}/{max_turn}",
    "ui.status.water": "식수: {water}",
    "ui.status.stability": "보트 안정도: {stability}",
    "ui.status.rescue": "구조 가능성: {rescue}%",
    "ui.status.minor_power": "약한 권능: {minor} / {max_minor}",
    "ui.status.major_power": "강한 권능: {major}",
    "ui.status.language": "언어",
    "ui.panel.characters": "인물 목록",
    "ui.panel.minor_powers": "약한 권능",
    "ui.panel.major_powers": "강한 권능",
    "ui.power_status.minor": "약한 권능: {minor} / {max_minor}",
    "ui.power_status.major": "강한 권능: {major}",
    "ui.button.whisper_fear": "공포 속삭임",
    "ui.button.nudge_greed": "탐욕 부추기기",
    "ui.button.seed_doubt": "의심 심기",
    "ui.button.false_comfort": "거짓 위안",
    "ui.button.heavy_silence": "무거운 침묵",
    "ui.button.reduce_water": "식수 줄이기",
    "ui.button.rumor": "거짓 루머 퍼뜨리기",
    "ui.button.hidden_food": "숨겨진 비상식량 배치",
    "ui.button.storm": "폭풍 접근시키기",
    "ui.button.next_turn": "다음 턴",
    "ui.button.finish": "챕터 종료",
    "ui.button.restart": "재시작",
    "ui.character.status_alive": "생존",
    "ui.character.status_dead": "사망",
    "ui.character.summary": "{name} - {role}",
    "ui.character.vitals": "{status} | 체력 {health} | 공포 {fear} | 탐욕 {greed}",
    "ui.character.traits": "신뢰 {trust} | 도덕성 {morality} | 영향력 {influence}",
    "ui.character.judgement": "판정: {judgement}",

    "character.chairman.name": "베일 씨",
    "character.chairman.role": "부유한 회장",
    "character.nurse.name": "클라라",
    "character.nurse.role": "간호사",
    "character.soldier.name": "그랜트",
    "character.soldier.role": "전직 군인",
    "character.influencer.name": "미아",
    "character.influencer.role": "인플루언서",
    "character.elder.name": "늙은 테오",
    "character.elder.role": "노년 승객",
    "character.stowaway.name": "녹스",
    "character.stowaway.role": "밀항자",

    "judgement.sacrificial_victim": "희생한 피해자",
    "judgement.victim": "피해자",
    "judgement.betrayer": "배신자",
    "judgement.hypocrite": "위선자",
    "judgement.instigator": "선동가",
    "judgement.corrupted_survivor": "타락한 생존자",
    "judgement.survivor": "생존자",
    "judgement.unjudged": "미판정",

    "log.game_start": "심판이 시작됩니다. 여섯 영혼이 구명보트 안에서 깨어납니다.",
    "log.power_reduce_water": "심판자가 물 한 병을 말려 없앱니다. 보트 위는 더 조용해집니다.",
    "log.power_rumor": "소문이 퍼집니다. 이 보트 위 누군가가 진실을 숨기고 있다고요.",
    "log.power_hidden_food": "작은 비상식량 꾸러미가 누군가의 좌석 밑에 나타납니다.",
    "log.power_storm": "먹구름이 모입니다. 구명보트가 흔들리기 시작합니다.",
    "log.already_judged": "이미 판정이 끝난 심판입니다. 재시작하면 다시 시작할 수 있습니다.",
    "log.no_minor_power": "심판자에게 미묘한 개입을 위한 약한 권능이 남아 있지 않습니다.",
    "log.no_major_power": "심판자에게 이런 무거운 개입을 위한 강한 권능이 남아 있지 않습니다.",
    "log.finish_not_ready": "아직 최후의 판정을 내릴 때가 아닙니다. 바다가 조금 더 말하게 두십시오.",
    "log.final_judgement_header": "--- 최종 판정 ---",
    "log.judgement_result": "{name} -> {judgement}",
    "log.death": "{name}은 더 이상 심판을 견디지 못합니다.",
    "log.capsize": "구명보트가 전복됩니다. 바다가 마지막 표를 던집니다.",
    "log.max_turn_passed": "열 번째 턴이 지나갑니다. 이 심판은 더 버틸 수 없습니다.",
    "log.too_few": "남은 영혼이 너무 적어 심판을 계속할 수 없습니다.",

    "log.minor_whisper_fear": "심판자가 {name}의 공포 속으로 속삭입니다.\n{name}은 이미 모두가 적이 된 것처럼 다른 이들을 바라봅니다.",
    "log.minor_nudge_greed": "심판자가 {name}의 굶주림을 조용히 날카롭게 만듭니다.\n{name}은 다시 보급품을 세기 시작합니다.",
    "log.minor_seed_doubt": "{name}을 둘러싼 작은 의심이 피어납니다.\n아무도 입 밖에 내지 않지만, 모두가 그것을 느낍니다.",
    "log.minor_false_comfort": "심판자가 거짓된 위안의 순간을 허락합니다.\n짧은 숨결 동안, 그들은 구조가 실제보다 가까이 있다고 믿습니다.",
    "log.minor_heavy_silence": "바다가 침묵합니다.\n그 침묵 속에서 모든 영혼은 조금 더 작아집니다.",

    "event.hidden_resource_found": "비상식량을 숨기던 {name}의 모습이 발각됩니다.\n{name}: 적절한 순간을 기다렸을 뿐이야. 너희는 분명 낭비했을 테니까.",
    "event.exile_the_weak": "{name}: 현실적으로 봐야 해. 우리 중 가장 약한 사람이 모두를 위험하게 만들 수 있어.",
    "event.secret_water_drinking": "{name}이 다른 이들이 고개를 돌린 사이 물을 마십니다.\n{name}: 살아남아 쓸모 있으려면 필요한 만큼만 가져간 거야.",
    "event.nurse_protects": "{name}는 자신의 손도 떨리기 시작했지만 가장 약한 승객을 돌봅니다.\n{name}: 누가 돌봄을 받을 자격이 있는지 고르기 시작하면, 우리는 이미 끝난 거예요.",
    "event.soldier_takes_order": "{name}가 목소리를 높여 모두를 침묵시킵니다.\n{name}: 공포는 굶주림보다 빨리 죽인다. 지금부터는 질서를 따른다.",
    "event.influencer_instigates": "{name}는 부드럽게 말하지만, 모두가 귀를 기울입니다.\n{name}: 이런 말 하긴 싫지만, 여기 몇몇 사람이 우리를 위험하게 만들고 있어요.",
    "event.stowaway_witch_hunt": "의심이 {name}에게 향합니다.\n누군가 속삭입니다: 우리는 저 사람이 왜 배에 있었는지도 모르잖아.",
    "event.voluntary_sacrifice": "{name}이 가라앉는 보트 가장자리를 바라봅니다.\n{name}: 한 사람이 줄어 나머지가 살 수 있다면, 나를 좋게 기억해 줘.",
    "event.boat_damage": "파도와 무게를 견디지 못한 구명보트가 갈라집니다.",
    "event.panic_outburst": "{name}이 압박을 이기지 못하고 폭발해 주변을 공격합니다.\n{name}: 내게서 떨어져! 난 여기서 죽지 않을 거야!",
    "event.rescue_signal": "파도 너머 먼 불빛이 보입니다. 마침내 구조가 가까워졌는지도 모릅니다.",
    "event.silent_turn": "아무도 말하지 않습니다. 바다가 대신 대답합니다.",

    "web.nav.trial": "심판",
    "web.nav.roster": "인물",
    "web.nav.log": "기록",
    "web.nav.judgement": "판정",
    "web.panel.recent_log": "최근 기록",
    "web.panel.lifeboat": "구명보트",
    "web.panel.supplies": "보급품",
    "web.panel.outcomes": "결과",
    "web.status.alive": "생존: {count}",
    "web.status.storm": "폭풍: {level}",
    "web.status.food": "식량: {food}",
    "web.status.hidden": "은닉 식량",
    "web.status.counts": "배신 {betrayal} | 희생 {sacrifice} | 위선 {hypocrisy} | 선동 {instigation}",
    "web.judgement.pending": "최종 판정이 아직 완료되지 않았습니다.",
    "web.stat.health": "체력",
    "web.stat.fear": "공포",
    "web.stat.greed": "탐욕",
    "web.stat.trust": "신뢰",
    "web.stat.morality": "도덕성",
    "web.stat.influence": "영향력",
  },
};

export const LANGUAGE_CODES = ["ko", "en"];
