export const en = {
  "ui.title.chapter_1": "Chapter 1 - Lifeboat of Greed",
  "ui.status.water": "Water: {water}",
  "ui.status.stability": "Stability: {stability}",
  "ui.status.rescue": "Rescue: {rescue}%",
  "ui.status.minor_power": "Minor: {minor} / {max_minor}",
  "ui.status.major_power": "Major: {major}",
  "ui.panel.characters": "Characters",
  "ui.panel.minor_powers": "Minor Powers",
  "ui.panel.major_powers": "Major Powers",
  "ui.power_status.minor": "Minor Power: {minor} / {max_minor}",
  "ui.power_status.major": "Major Power: {major}",
  "ui.button.whisper_fear": "Whisper Fear",
  "ui.button.nudge_greed": "Nudge Greed",
  "ui.button.seed_doubt": "Seed Doubt",
  "ui.button.false_comfort": "False Comfort",
  "ui.button.heavy_silence": "Heavy Silence",
  "ui.button.reduce_water": "Reduce Water",
  "ui.button.rumor": "Spread False Rumor",
  "ui.button.hidden_food": "Place Hidden Food",
  "ui.button.storm": "Approach Storm",
  "ui.character.vitals": "{status} | HP {health} | Fear {fear} | Greed {greed}",
  "ui.character.traits": "Trust {trust} | Morality {morality} | Influence {influence}",
  "character.chairman.name": "Mr. Vale",
  "character.chairman.role": "Wealthy Chairman",
  "character.nurse.name": "Clara",
  "character.nurse.role": "Nurse",
  "character.soldier.name": "Grant",
  "character.soldier.role": "Ex-Soldier",
  "character.influencer.name": "Mia",
  "character.influencer.role": "Influencer",
  "character.elder.name": "Old Theo",
  "character.elder.role": "Elderly Passenger",
  "character.stowaway.name": "Nox",
  "character.stowaway.role": "Stowaway",
  "judgement.sacrificial_victim": "Sacrificial Victim",
  "judgement.victim": "Victim",
  "judgement.betrayer": "Betrayer",
  "judgement.hypocrite": "Hypocrite",
  "judgement.instigator": "Instigator",
  "judgement.corrupted_survivor": "Corrupted Survivor",
  "judgement.exiled": "Exiled Victim",
  "judgement.survivor": "Survivor",
  "judgement.unjudged": "Unjudged",
  "log.game_start": "The trial begins. Six souls wake inside a lifeboat.",
  "log.power_reduce_water": "The Judge dries one bottle of water. The boat grows quieter.",
  "log.power_rumor": "A rumor spreads: someone on this boat has been hiding the truth.",
  "log.power_hidden_food": "A small packet of emergency food appears beneath someone's seat.",
  "log.power_storm": "Dark clouds gather. The lifeboat begins to shake.",
  "log.finish_not_ready": "The trial is not ripe for final judgement. Let the sea speak longer.",
  "log.death": "{name} can no longer endure the trial.",
  "log.final_overload": "The last turn arrives without rescue. The overloaded boat demands one final loss.",
  "log.capsize": "The lifeboat capsizes. The sea takes the final vote.",
  "log.too_few": "Too few souls remain to continue the trial.",
  "log.minor_whisper_fear": "The Judge whispers into {name}'s fear.\n{name} looks at the others as if they are already enemies.",
  "log.minor_nudge_greed": "The Judge gently sharpens {name}'s hunger.\n{name} starts counting the supplies again.",
  "log.minor_seed_doubt": "A small doubt blooms around {name}.\nNo one says it aloud, but everyone feels it.",
  "log.minor_false_comfort": "The Judge grants a moment of false comfort.\nFor a breath, they believe rescue is closer than it is.",
  "log.minor_heavy_silence": "The sea falls silent.\nIn that silence, every soul becomes a little smaller.",
  "event.hidden_resource_found": "{name} is caught hiding emergency food.\n{name}: I was saving it for the right moment. You would have wasted it.",
  "event.exile_the_weak": "{name}: We need to be realistic. The weakest among us may doom everyone.",
  "event.secret_water_drinking": "{name} drinks from the water supply while the others look away.\n{name}: I only took what I needed to stay useful.",
  "event.nurse_protects": "{name} tends to the weakest passenger, even as her own hands begin to shake.\n{name}: If we start choosing who deserves care, we are already lost.",
  "event.soldier_takes_order": "{name} raises his voice and forces everyone into silence.\n{name}: Panic kills faster than hunger. From now on, we follow order.",
  "event.influencer_instigates": "{name} speaks softly, but everyone listens.\n{name}: I hate to say this, but some people here are making us unsafe.",
  "event.stowaway_witch_hunt": "Suspicion turns toward {name}.\nSomeone whispers: We do not even know why he was on the ship.",
  "event.voluntary_sacrifice": "{name} looks at the sinking edge of the boat.\n{name}: If one less body gives the rest of you a chance, then remember me kindly.",
  "event.boat_damage": "The lifeboat cracks under the weight and the waves.",
  "event.panic_outburst": "{name} snaps under the pressure and lashes out.\n{name}: Stay away from me! I will not die here!",
  "event.rescue_signal": "A distant light appears beyond the waves. Rescue may finally be near.",
  "event.silent_turn": "No one speaks. The sea answers for them.",
  "event.leak_spreads": "Water creeps through the seams faster than hands can bail it out.",
  "event.supplies_crack_hull": "The supplies slide hard against the side. The hull answers with a sharp crack.",
  "event.public_accusation": "{actor} points toward {target} before anyone else can speak.\n{actor}: One burden too many will drown us all.",
  "event.survival_pact": "{actor} and {target} fall quiet, then begin guarding each other's words.",
  "event.exile_vote": "The boat chooses a burden. {target} is thrown into the sea.",
  "event.exile_resisted": "{target} survives the vote, but the circle around them does not close again.",
  "event.failed_exile_violent": "The failed vote turns violent. {actor} and {target} collide in panic.",
  "event.voluntary_sacrifice_new": "{target} steps over the edge before the others can name them.\n{target}: Let the rest of you be lighter.",
  "card.description.whisper_fear": "Raise the most frightened passenger's fear and lower their trust.",
  "card.description.nudge_greed": "Push the greediest passenger toward more selfish choices.",
  "card.description.seed_doubt": "Make the least trusting passenger a stronger focus of suspicion.",
  "card.description.false_comfort": "Give everyone brief relief while lowering rescue odds.",
  "card.description.heavy_silence": "Let silence raise fear and despair across the boat.",
  "card.description.reduce_water": "Remove water and sharply raise everyone's fear.",
  "card.description.rumor": "Spread a rumor that damages trust across the boat.",
  "card.description.hidden_food": "Give hidden food to the greediest passenger.",
  "card.description.storm": "Call in a storm that pressures the boat and passengers.",
  "web.panel.lifeboat": "Lifeboat",
  "web.panel.supplies": "Supplies",
  "web.status.storm": "Storm: {level}",
  "web.status.food": "Food: {food}",
  "web.status.hidden": "Hidden food",
  "web.status.counts": "Betrayal {betrayal} | Sacrifice {sacrifice} | Hypocrisy {hypocrisy} | Instigation {instigation}",
  "web.count.betrayal": "Betrayal",
  "web.count.sacrifice": "Sacrifice",
  "web.count.hypocrisy": "Hypocrisy",
  "web.count.instigation": "Instigation",
  "web.log.death_alert": "Death occurred: {name}",
  "web.log.unknown_deceased": "Someone",
  "web.guide.color": "Color guide: red = high fear, yellow = high greed, green = high morality, gray = dead.",
  "web.panel.crisis": "Crisis",
  "web.status.hull": "Hull Damage: {value}",
  "web.status.ingress": "Water Ingress: {value}",
  "web.status.load": "Load Pressure: {value}",
  "web.status.despair": "Despair: {value}",
  "web.social.target": "Target Pressure: {value}",
  "web.social.target_label": "Target",
  "web.social.accusation": "Suspicion",
  "web.social.allies": "Allies: {names}",
  "web.social.enemies": "Enemies: {names}",
  "web.stat.health": "HP",
  "web.stat.fear": "Fear",
  "web.stat.greed": "Greed",
  "web.stat.trust": "Trust",
  "web.stat.morality": "Morality",
  "web.stat.influence": "Influence"
};
