export const ko = {
  "ui.title.chapter_1": "1장 - 탐욕의 구명보트",
  "ui.status.water": "식수: {water}",
  "ui.status.stability": "보트 안정도: {stability}",
  "ui.status.rescue": "구조 가능성: {rescue}%",
  "ui.status.minor_power": "약한 권능: {minor} / {max_minor}",
  "ui.status.major_power": "강한 권능: {major}",
  "ui.panel.characters": "인물 목록",
  "ui.panel.minor_powers": "약한 권능",
  "ui.panel.major_powers": "강한 권능",
  "ui.power_status.minor": "약한 권능: {minor} / {max_minor}",
  "ui.power_status.major": "강한 권능: {major}",
  "ui.button.whisper_fear": "공포 속삭임",
  "ui.button.nudge_greed": "탐욕 부추기기",
  "ui.button.seed_doubt": "의심 심기",
  "ui.button.false_comfort": "거짓 위안",
  "ui.button.heavy_silence": "무거운 침묵",
  "ui.button.reduce_water": "식수 줄이기",
  "ui.button.rumor": "거짓 루머 퍼뜨리기",
  "ui.button.hidden_food": "숨겨진 비상식량 배치",
  "ui.button.storm": "폭풍 접근시키기",
  "ui.character.vitals": "{status} | 체력 {health} | 공포 {fear} | 탐욕 {greed}",
  "ui.character.traits": "신뢰 {trust} | 도덕성 {morality} | 영향력 {influence}",
  "character.chairman.name": "베일 씨",
  "character.chairman.role": "부유한 회장",
  "character.nurse.name": "클라라",
  "character.nurse.role": "간호사",
  "character.soldier.name": "그랜트",
  "character.soldier.role": "전직 군인",
  "character.influencer.name": "미아",
  "character.influencer.role": "인플루언서",
  "character.elder.name": "늙은 테오",
  "character.elder.role": "노년 승객",
  "character.stowaway.name": "녹스",
  "character.stowaway.role": "밀항자",
  "judgement.sacrificial_victim": "희생한 피해자",
  "judgement.victim": "피해자",
  "judgement.betrayer": "배신자",
  "judgement.hypocrite": "위선자",
  "judgement.instigator": "선동가",
  "judgement.corrupted_survivor": "타락한 생존자",
  "judgement.exiled": "추방된 피해자",
  "judgement.survivor": "생존자",
  "judgement.unjudged": "미판정",
  "log.game_start": "심판이 시작됩니다. 여섯 영혼이 구명보트 안에서 깨어납니다.",
  "log.power_reduce_water": "심판자가 물 한 병을 말려 없앱니다. 보트 위는 더 조용해집니다.",
  "log.power_rumor": "소문이 퍼집니다. 이 보트 위 누군가가 진실을 숨기고 있다고요.",
  "log.power_hidden_food": "작은 비상식량 꾸러미가 누군가의 좌석 밑에 나타납니다.",
  "log.power_storm": "먹구름이 모입니다. 구명보트가 흔들리기 시작합니다.",
  "log.finish_not_ready": "아직 최후의 판정을 내릴 때가 아닙니다. 바다가 조금 더 말하게 두십시오.",
  "log.death": "{name}은 더 이상 심판을 견디지 못합니다.",
  "log.final_overload": "구조 없이 마지막 턴이 옵니다. 과적된 보트가 마지막 손실을 요구합니다.",
  "log.capsize": "구명보트가 전복됩니다. 바다가 마지막 표를 던집니다.",
  "log.too_few": "남은 영혼이 너무 적어 심판을 계속할 수 없습니다.",
  "log.minor_whisper_fear": "심판자가 {name}의 공포 속으로 속삭입니다.\n{name}은 이미 모두가 적이 된 것처럼 다른 이들을 바라봅니다.",
  "log.minor_nudge_greed": "심판자가 {name}의 굶주림을 조용히 날카롭게 만듭니다.\n{name}은 다시 보급품을 세기 시작합니다.",
  "log.minor_seed_doubt": "{name}을 둘러싼 작은 의심이 피어납니다.\n아무도 입 밖에 내지 않지만, 모두가 그것을 느낍니다.",
  "log.minor_false_comfort": "심판자가 거짓된 위안의 순간을 허락합니다.\n짧은 숨결 동안, 그들은 구조가 실제보다 가까이 있다고 믿습니다.",
  "log.minor_heavy_silence": "바다가 침묵합니다.\n그 침묵 속에서 모든 영혼은 조금 더 작아집니다.",
  "event.hidden_resource_found": "비상식량을 숨기던 {name}의 모습이 발각됩니다.\n{name}: 적절한 순간을 기다렸을 뿐이야. 너희는 분명 낭비했을 테니까.",
  "event.exile_the_weak": "{name}: 현실적으로 봐야 해. 우리 중 가장 약한 사람이 모두를 위험하게 만들 수 있어.",
  "event.secret_water_drinking": "{name}이 다른 이들이 고개를 돌린 사이 물을 마십니다.\n{name}: 살아남아 쓸모 있으려면 필요한 만큼만 가져간 거야.",
  "event.nurse_protects": "{name}는 자신의 손도 떨리기 시작했지만 가장 약한 승객을 돌봅니다.\n{name}: 누가 돌봄을 받을 자격이 있는지 고르기 시작하면, 우리는 이미 끝난 거예요.",
  "event.soldier_takes_order": "{name}가 목소리를 높여 모두를 침묵시킵니다.\n{name}: 공포는 굶주림보다 빨리 죽인다. 지금부터는 질서를 따른다.",
  "event.influencer_instigates": "{name}는 부드럽게 말하지만, 모두가 귀를 기울입니다.\n{name}: 이런 말 하긴 싫지만, 여기 몇몇 사람이 우리를 위험하게 만들고 있어요.",
  "event.stowaway_witch_hunt": "의심이 {name}에게 향합니다.\n누군가 속삭입니다: 우리는 저 사람이 왜 배에 있었는지도 모르잖아.",
  "event.voluntary_sacrifice": "{name}이 가라앉는 보트 가장자리를 바라봅니다.\n{name}: 한 사람이 줄어 나머지가 살 수 있다면, 나를 좋게 기억해 줘.",
  "event.boat_damage": "파도와 무게를 견디지 못한 구명보트가 갈라집니다.",
  "event.panic_outburst": "{name}이 압박을 이기지 못하고 폭발해 주변을 공격합니다.\n{name}: 내게서 떨어져! 난 여기서 죽지 않을 거야!",
  "event.rescue_signal": "파도 너머 먼 불빛이 보입니다. 마침내 구조가 가까워졌는지도 모릅니다.",
  "event.silent_turn": "아무도 말하지 않습니다. 바다가 대신 대답합니다.",
  "event.leak_spreads": "손으로 퍼내는 속도보다 빠르게 물이 틈새로 스며듭니다.",
  "event.supplies_crack_hull": "보급품이 보트 옆면을 세게 밀칩니다. 선체가 날카롭게 갈라지는 소리로 답합니다.",
  "event.public_accusation": "{actor}가 누구보다 먼저 {target}을 가리킵니다.\n{actor}: 짐 하나가 너무 많으면 우리 모두가 가라앉아.",
  "event.survival_pact": "{actor}와 {target}이 조용해지더니, 서로의 말을 지키기 시작합니다.",
  "event.exile_vote": "보트가 짐을 하나 고릅니다. {target}은 바다로 던져집니다.",
  "event.exile_resisted": "{target}은 투표에서 살아남지만, 그들을 둘러싼 원은 다시 닫히지 않습니다.",
  "event.failed_exile_violent": "실패한 투표가 폭력으로 번집니다. {actor}와 {target}이 공포 속에서 부딪힙니다.",
  "event.voluntary_sacrifice_new": "{target}이 누군가 이름을 부르기 전에 보트 밖으로 발을 내딛습니다.\n{target}: 남은 너희라도 가벼워져.",
  "web.panel.lifeboat": "구명보트",
  "web.panel.supplies": "보급품",
  "web.status.storm": "폭풍: {level}",
  "web.status.food": "식량: {food}",
  "web.status.hidden": "은닉 식량",
  "web.status.counts": "배신 {betrayal} | 희생 {sacrifice} | 위선 {hypocrisy} | 선동 {instigation}",
  "web.count.betrayal": "배신",
  "web.count.sacrifice": "희생",
  "web.count.hypocrisy": "위선",
  "web.count.instigation": "선동",
  "web.guide.color": "색상: 붉음=공포 높음, 노랑=탐욕 높음, 초록=도덕성 높음, 회색=사망.",
  "web.panel.crisis": "위기",
  "web.status.hull": "선체 파손도: {value}",
  "web.status.ingress": "침수도: {value}",
  "web.status.load": "하중 압박: {value}",
  "web.status.despair": "절망: {value}",
  "web.social.target": "표적 압박: {value}",
  "web.social.target_label": "표적",
  "web.social.accusation": "의심",
  "web.social.allies": "동맹: {names}",
  "web.social.enemies": "적대: {names}",
  "web.stat.health": "체력",
  "web.stat.fear": "공포",
  "web.stat.greed": "탐욕",
  "web.stat.trust": "신뢰",
  "web.stat.morality": "도덕성",
  "web.stat.influence": "영향력"
};
