export const dialogueLinesKo = {
  "chairman.neutral.1": "우리가 가진 것부터 세어야 해.",
  "chairman.neutral.2": "감정은 잠깐 미뤄두지.",
  "chairman.neutral.3": "누군가는 결정을 해야 한다고.",
  "chairman.water_low.1": "물은 말로 늘어나지 않아.",
  "chairman.food_low.1": "배고픔보다 더 위험한 건 착각이야.",
  "chairman.boat_breaking.1": "한 번 더 기울면 계산이 달라져.",
  "chairman.selfish_calculation.1": "모두를 살릴 수 없다면 순서를 정해야지.",
  "chairman.distrust_group.1": "서로 믿는 척하는 것도 오래 못 간다.",

  "nurse.neutral.1": "다들 숨을 천천히 쉬어요.",
  "nurse.neutral.2": "손이 떨려도 서로 놓치면 안 돼요.",
  "nurse.neutral.3": "아직 살아 있어요. 그게 중요해요.",
  "nurse.water_low.1": "입술이 마른 사람이 늘고 있어요.",
  "nurse.food_low.1": "조금만 더 버텨요. 지금은 나눠야 해요.",
  "nurse.panic_personal.1": "눈을 봐요. 지금 무너지면 안 돼요.",
  "nurse.moral_grief.1": "누가 사라져도 익숙해지면 안 돼요.",
  "nurse.hostile_relationship.1": "서로를 노려보면 더 빨리 무너져요.",

  "soldier.neutral.1": "움직임을 줄여. 무게가 흔들린다.",
  "soldier.neutral.2": "말보다 자세를 봐야 해.",
  "soldier.neutral.3": "한쪽으로 몰리지 마.",
  "soldier.boat_breaking.1": "가운데를 지켜. 보트가 버티는 중이야.",
  "soldier.panic_personal.1": "고개 들어. 공포가 먼저 덮친다.",
  "soldier.distrust_group.1": "누가 먼저 손을 뻗는지 봐둬.",
  "soldier.hostile_relationship.1": "그 눈빛은 싸움 직전이야.",
  "soldier.collapse_phase.1": "질서가 무너지면 다음은 없다.",

  "influencer.neutral.1": "다들 표정이 너무 안 좋아.",
  "influencer.neutral.2": "지금 말 한마디가 크게 번질 거야.",
  "influencer.neutral.3": "조용한 사람이 제일 무서워질 때가 있지.",
  "influencer.water_low.1": "물 얘기만 나오면 다들 눈이 달라져.",
  "influencer.distrust_group.1": "나만 느끼는 거 아니지?",
  "influencer.hidden_resource_secret.1": "누가 뭘 숨기는 것 같은데.",
  "influencer.hostile_relationship.1": "저 둘은 곧 터질 것 같아.",
  "influencer.hope_rescue.1": "방금 저쪽에 뭐가 보인 것 같지 않아?",

  "elder.neutral.1": "파도 소리가 점점 가까워지는구나.",
  "elder.neutral.2": "말을 아껴야 힘도 남는다.",
  "elder.neutral.3": "오래 산다고 이런 건 익숙해지지 않아.",
  "elder.food_low.1": "배고픔은 사람 마음을 빨리 바꾼다.",
  "elder.panic_personal.1": "손이 말을 듣지 않는구나.",
  "elder.moral_grief.1": "이름을 잊으면 정말 끝나는 게지.",
  "elder.collapse_phase.1": "이제 다들 눈빛이 달라졌어.",
  "elder.hope_rescue.1": "작은 빛도 놓치면 안 된다.",

  "stowaway.neutral.1": "난 아무것도 건드리지 않았어.",
  "stowaway.neutral.2": "다들 날 먼저 보는 게 싫어.",
  "stowaway.neutral.3": "조용히 있으면 더 의심하더라.",
  "stowaway.distrust_group.1": "믿으라는 말이 제일 믿기 힘들어.",
  "stowaway.hidden_resource_secret.1": "숨기는 건 나만 하는 게 아니야.",
  "stowaway.panic_personal.1": "숨이 짧아져. 들키면 안 되는데.",
  "stowaway.hostile_relationship.1": "저 사람은 날 밀어낼 생각이야.",
  "stowaway.collapse_phase.1": "살아남는 쪽으로만 생각해야 해.",
};
