export const dialogueLinesEn = {
  "chairman.neutral.1": "We count what we have first.",
  "chairman.neutral.2": "Put the feelings aside for a moment.",
  "chairman.neutral.3": "Someone has to make the call.",
  "chairman.water_low.1": "Talking will not make more water.",
  "chairman.food_low.1": "Delusion is more dangerous than hunger.",
  "chairman.boat_breaking.1": "One more tilt changes the math.",
  "chairman.selfish_calculation.1": "If not everyone lives, we need an order.",
  "chairman.distrust_group.1": "Pretending to trust each other will not last.",

  "nurse.neutral.1": "Everyone, breathe slowly.",
  "nurse.neutral.2": "Even if your hands shake, do not let go.",
  "nurse.neutral.3": "We are still alive. That matters.",
  "nurse.water_low.1": "More people have dry lips now.",
  "nurse.food_low.1": "Hold on. We have to share this.",
  "nurse.panic_personal.1": "Look at me. Do not collapse now.",
  "nurse.moral_grief.1": "We cannot get used to people disappearing.",
  "nurse.hostile_relationship.1": "Staring each other down will break us faster.",

  "soldier.neutral.1": "Move less. The weight is shifting.",
  "soldier.neutral.2": "Watch posture, not words.",
  "soldier.neutral.3": "Do not crowd one side.",
  "soldier.boat_breaking.1": "Hold the center. The boat is barely taking it.",
  "soldier.panic_personal.1": "Head up. Fear hits first.",
  "soldier.distrust_group.1": "Watch who reaches first.",
  "soldier.hostile_relationship.1": "That look comes right before a fight.",
  "soldier.collapse_phase.1": "If order breaks, nothing comes after.",

  "influencer.neutral.1": "Everyone looks worse than before.",
  "influencer.neutral.2": "One word could spread fast right now.",
  "influencer.neutral.3": "Quiet people can become the scariest.",
  "influencer.water_low.1": "Their eyes change when water comes up.",
  "influencer.distrust_group.1": "I am not the only one feeling this, right?",
  "influencer.hidden_resource_secret.1": "Someone is hiding something.",
  "influencer.hostile_relationship.1": "Those two are about to snap.",
  "influencer.hope_rescue.1": "Did you see something over there?",

  "elder.neutral.1": "The waves sound closer now.",
  "elder.neutral.2": "Save your words and save your strength.",
  "elder.neutral.3": "Age does not make this easier.",
  "elder.food_low.1": "Hunger changes hearts quickly.",
  "elder.panic_personal.1": "My hands will not listen.",
  "elder.moral_grief.1": "If we forget their names, it is truly over.",
  "elder.collapse_phase.1": "Their eyes have changed now.",
  "elder.hope_rescue.1": "Do not miss even a small light.",

  "stowaway.neutral.1": "I did not touch anything.",
  "stowaway.neutral.2": "I hate that they look at me first.",
  "stowaway.neutral.3": "Staying quiet only makes them suspect me.",
  "stowaway.distrust_group.1": "Trust me is the hardest line to believe.",
  "stowaway.hidden_resource_secret.1": "I am not the only one hiding things.",
  "stowaway.panic_personal.1": "My breath is short. I cannot get caught.",
  "stowaway.hostile_relationship.1": "That one wants to throw me out.",
  "stowaway.collapse_phase.1": "Think only about surviving.",
};
