export const LOG_LIMIT = 120;

export const CLAMPED_STATS = [
  "health",
  "fear",
  "greed",
  "trust",
  "morality",
  "influence",
];

export const TRACKED_STAT_DELTAS = [
  "health",
  "fear",
  "greed",
  "trust",
  "morality",
  "influence",
  "betrayal_count",
  "sacrifice_count",
  "hypocrisy_count",
  "instigation_count",
  "accusation_score",
  "target_pressure",
];

export const TRACKED_BOAT_DELTAS = [
  "turn",
  "water",
  "food",
  "stability",
  "rescue_chance",
  "storm_level",
  "hull_damage",
  "water_ingress",
  "load_pressure",
  "despair",
  "minor_power",
  "major_power",
  "alive_count",
];

export const DEFAULT_BOAT_STATE = {
  turn: 1,
  max_turn: 18,
  water: 5,
  food: 3,
  stability: 70,
  rescue_chance: 30,
  storm_level: 0,
  hull_damage: 0,
  water_ingress: 0,
  load_pressure: 32,
  despair: 0,
  rescue_signal_seen: false,
  event_history: [],
  event_cooldowns: {},
  minor_power: 3,
  max_minor_power: 3,
  major_power: 4,
  chapter_finished: false,
  judgement_done: false,
};

export const DEFAULT_CHARACTERS = [
  {
    id: "chairman",
    name: "Mr. Vale",
    name_key: "character.chairman.name",
    role: "Wealthy Chairman",
    role_key: "character.chairman.role",
    alive: true,
    health: 100,
    fear: 35,
    greed: 85,
    trust: 40,
    morality: 30,
    influence: 70,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
  {
    id: "nurse",
    name: "Clara",
    name_key: "character.nurse.name",
    role: "Nurse",
    role_key: "character.nurse.role",
    alive: true,
    health: 100,
    fear: 30,
    greed: 20,
    trust: 70,
    morality: 85,
    influence: 45,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
  {
    id: "soldier",
    name: "Grant",
    name_key: "character.soldier.name",
    role: "Ex-Soldier",
    role_key: "character.soldier.role",
    alive: true,
    health: 100,
    fear: 25,
    greed: 45,
    trust: 50,
    morality: 55,
    influence: 75,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
  {
    id: "influencer",
    name: "Mia",
    name_key: "character.influencer.name",
    role: "Influencer",
    role_key: "character.influencer.role",
    alive: true,
    health: 100,
    fear: 45,
    greed: 65,
    trust: 55,
    morality: 45,
    influence: 80,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
  {
    id: "elder",
    name: "Old Theo",
    name_key: "character.elder.name",
    role: "Elderly Passenger",
    role_key: "character.elder.role",
    alive: true,
    health: 70,
    fear: 50,
    greed: 15,
    trust: 60,
    morality: 75,
    influence: 20,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
  {
    id: "stowaway",
    name: "Nox",
    name_key: "character.stowaway.name",
    role: "Stowaway",
    role_key: "character.stowaway.role",
    alive: true,
    health: 90,
    fear: 55,
    greed: 50,
    trust: 20,
    morality: 50,
    influence: 25,
    has_hidden_resource: false,
    betrayal_count: 0,
    sacrifice_count: 0,
    hypocrisy_count: 0,
    instigation_count: 0,
    alliances: [],
    enemies: [],
    accusation_score: 0,
    target_pressure: 0,
    death_reason: "",
    judgement: "",
  },
];
