export const cardDefinitions = [
  {
    id: "card_whisper_fear",
    sourcePowerId: "whisper_fear",
    tier: "minor",
    rarity: "common",
    labelKey: "ui.button.whisper_fear",
    descriptionKey: "card.description.whisper_fear",
    effectId: "power.whisper_fear",
    targetPolicy: "auto_highest_fear",
    tags: ["fear", "social"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_nudge_greed",
    sourcePowerId: "nudge_greed",
    tier: "minor",
    rarity: "common",
    labelKey: "ui.button.nudge_greed",
    descriptionKey: "card.description.nudge_greed",
    effectId: "power.nudge_greed",
    targetPolicy: "auto_highest_greed",
    tags: ["greed", "resource"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_seed_doubt",
    sourcePowerId: "seed_doubt",
    tier: "minor",
    rarity: "common",
    labelKey: "ui.button.seed_doubt",
    descriptionKey: "card.description.seed_doubt",
    effectId: "power.seed_doubt",
    targetPolicy: "auto_lowest_trust",
    tags: ["doubt", "social"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_false_comfort",
    sourcePowerId: "false_comfort",
    tier: "minor",
    rarity: "common",
    labelKey: "ui.button.false_comfort",
    descriptionKey: "card.description.false_comfort",
    effectId: "power.false_comfort",
    targetPolicy: "all_alive",
    tags: ["hope", "group"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_heavy_silence",
    sourcePowerId: "heavy_silence",
    tier: "minor",
    rarity: "common",
    labelKey: "ui.button.heavy_silence",
    descriptionKey: "card.description.heavy_silence",
    effectId: "power.heavy_silence",
    targetPolicy: "all_alive",
    tags: ["silence", "group"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_reduce_water",
    sourcePowerId: "reduce_water",
    tier: "major",
    rarity: "rare",
    labelKey: "ui.button.reduce_water",
    descriptionKey: "card.description.reduce_water",
    effectId: "power.reduce_water",
    targetPolicy: "all_alive",
    tags: ["water", "pressure"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_rumor",
    sourcePowerId: "rumor",
    tier: "major",
    rarity: "rare",
    labelKey: "ui.button.rumor",
    descriptionKey: "card.description.rumor",
    effectId: "power.rumor",
    targetPolicy: "auto_lowest_trust",
    tags: ["doubt", "social"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_hidden_food",
    sourcePowerId: "hidden_food",
    tier: "major",
    rarity: "rare",
    labelKey: "ui.button.hidden_food",
    descriptionKey: "card.description.hidden_food",
    effectId: "power.hidden_food",
    targetPolicy: "auto_highest_greed",
    tags: ["food", "temptation"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
  {
    id: "card_storm",
    sourcePowerId: "storm",
    tier: "major",
    rarity: "rare",
    labelKey: "ui.button.storm",
    descriptionKey: "card.description.storm",
    effectId: "power.storm",
    targetPolicy: "all_alive",
    tags: ["storm", "environment"],
    cooldownSeconds: 0,
    exhaustOnPlay: false,
  },
];

export const cardDefinitionById = Object.fromEntries(
  cardDefinitions.map((card) => [card.id, card]),
);

export function findCardDefinition(cardId) {
  return cardDefinitionById[cardId] || null;
}

export const cards = {
  definitions: cardDefinitions,
  byId: cardDefinitionById,
};
