export const COMMON_TRANSLATIONS = {
  "en": {
    "language.en": "English",
    "language.ko": "Korean",
    "ui.title.game": "The Judge of Survival",
    "ui.status.turn": "Turn: {turn}/{max_turn}",
    "ui.status.language": "Language",
    "ui.button.next_turn": "Next Turn",
    "ui.button.finish": "Finish Chapter",
    "ui.button.restart": "Restart",
    "ui.character.status_alive": "Alive",
    "ui.character.status_dead": "Dead",
    "ui.character.summary": "{name} - {role}",
    "ui.character.judgement": "Judgement: {judgement}",
    "log.already_judged": "The trial is already judged. Restart to begin again.",
    "log.no_minor_power": "The Judge has no minor power left for subtle interference.",
    "log.no_major_power": "The Judge has no major power left for such a heavy intervention.",
    "log.card_paused": "Cards cannot be played while the simulation is paused.",
    "log.card_not_in_hand": "That card is no longer in hand.",
    "log.final_judgement_header": "--- Final Judgement ---",
    "log.judgement_result": "{name} -> {judgement}",
    "log.max_turn_passed": "The final turn passes. The trial can hold no more.",
    "web.nav.trial": "Trial",
    "web.nav.roster": "Roster",
    "web.nav.log": "Log",
    "web.nav.judgement": "Judgement",
    "web.panel.recent_log": "Recent Log",
    "web.panel.outcomes": "Outcomes",
    "web.status.alive": "Alive: {count}",
    "web.judgement.pending": "Final judgement is not complete.",
    "web.event_overlay.major_event": "Major Event",
    "web.event_overlay.next_image": "Next Image",
    "web.event_overlay.close": "Close",
    "web.social.none": "None",
    "web.save": "Save",
    "web.continue": "Continue",
    "web.time.pause": "Pause",
    "web.time.resume": "Resume",
    "web.time.speed_1x": "1x",
    "web.time.speed_2x": "2x",
    "web.time.elapsed": "{elapsed} / {duration}",
    "web.time.next_event": "Event {time}",
    "web.time.next_card": "Card {time}",
    "web.card.hand": "Cards",
    "web.card.empty": "No cards in hand.",
    "web.card.paused": "Paused",
    "web.card.pile_counts": "Draw {draw} | Discard {discard} | Exhaust {exhaust}",
    "web.card.play": "Play"
  },
  "ko": {
    "language.en": "영어",
    "language.ko": "한국어",
    "ui.title.game": "생존의 심판자",
    "ui.status.turn": "턴: {turn}/{max_turn}",
    "ui.status.language": "언어",
    "ui.button.next_turn": "다음 턴",
    "ui.button.finish": "챕터 종료",
    "ui.button.restart": "재시작",
    "ui.character.status_alive": "생존",
    "ui.character.status_dead": "사망",
    "ui.character.summary": "{name} - {role}",
    "ui.character.judgement": "판정: {judgement}",
    "log.already_judged": "이미 판정이 끝난 심판입니다. 재시작하면 다시 시작할 수 있습니다.",
    "log.no_minor_power": "심판자에게 미묘한 개입을 위한 약한 권능이 남아 있지 않습니다.",
    "log.no_major_power": "심판자에게 이런 무거운 개입을 위한 강한 권능이 남아 있지 않습니다.",
    "log.card_paused": "일시정지 중에는 카드를 사용할 수 없습니다.",
    "log.card_not_in_hand": "이미 손패에 없는 카드입니다.",
    "log.final_judgement_header": "--- 최종 판정 ---",
    "log.judgement_result": "{name} -> {judgement}",
    "log.max_turn_passed": "마지막 턴이 지나갑니다. 이 심판은 더 버틸 수 없습니다.",
    "web.nav.trial": "심판",
    "web.nav.roster": "인물",
    "web.nav.log": "기록",
    "web.nav.judgement": "판정",
    "web.panel.recent_log": "최근 기록",
    "web.panel.outcomes": "결과",
    "web.status.alive": "생존: {count}",
    "web.judgement.pending": "최종 판정이 아직 완료되지 않았습니다.",
    "web.event_overlay.major_event": "중대 이벤트",
    "web.event_overlay.next_image": "다음 이미지",
    "web.event_overlay.close": "닫기",
    "web.social.none": "없음",
    "web.save": "저장",
    "web.continue": "이어하기",
    "web.time.pause": "정지",
    "web.time.resume": "재생",
    "web.time.speed_1x": "1배속",
    "web.time.speed_2x": "2배속",
    "web.time.elapsed": "{elapsed} / {duration}",
    "web.time.next_event": "이벤트 {time}",
    "web.time.next_card": "카드 {time}",
    "web.card.hand": "카드",
    "web.card.empty": "손패에 카드가 없습니다.",
    "web.card.paused": "일시정지",
    "web.card.pile_counts": "덱 {draw} | 버림 {discard} | 소멸 {exhaust}",
    "web.card.play": "사용"
  }
};

export const TRANSLATIONS = COMMON_TRANSLATIONS;

export const LANGUAGE_CODES = ["ko", "en"];
