export const COMMAND_TYPES = {
  NEXT_TURN: "NEXT_TURN",
  USE_POWER: "USE_POWER",
  USE_MINOR_POWER: "USE_MINOR_POWER",
  USE_MAJOR_POWER: "USE_MAJOR_POWER",
  PLAY_CARD: "PLAY_CARD",
  ADVANCE_TIME: "ADVANCE_TIME",
  SET_PAUSED: "SET_PAUSED",
  SET_TIME_SCALE: "SET_TIME_SCALE",
  FINISH_CHAPTER: "FINISH_CHAPTER",
  RESTART: "RESTART",
};
