export const COMMAND_TYPES = {
  NEXT_TURN: "NEXT_TURN",
  USE_POWER: "USE_POWER",
  USE_MINOR_POWER: "USE_MINOR_POWER",
  USE_MAJOR_POWER: "USE_MAJOR_POWER",
  FINISH_CHAPTER: "FINISH_CHAPTER",
  RESTART: "RESTART",
};
